version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "10:00"
    target-branch: master
    open-pull-requests-limit: 10
    versioning-strategy: increase
    reviewers:
      - "pi-hole/docs-maintainers"
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "10:00"
    target-branch: master
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    reviewers:
      - "pi-hole/docs-maintainers"
    groups:
      pip-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "10:00"
    reviewers:
      - "pi-hole/docs-maintainers"
    groups:
      github_action-dependencies:
        patterns:
          - "*"
    target-branch: master

# As above, but for development-v6
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "10:00"
    target-branch: release/v6.0
    open-pull-requests-limit: 10
    versioning-strategy: increase
    reviewers:
      - "pi-hole/docs-maintainers"
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "10:00"
    target-branch: release/v6.0
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    reviewers:
      - "pi-hole/docs-maintainers"
    groups:
      pip-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "10:00"
    reviewers:
      - "pi-hole/docs-maintainers"
    groups:
      github_action-dependencies:
        patterns:
          - "*"
    target-branch: release/v6.0
