name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

env:
  FORCE_COLOR: 2
  NODE: 22
  PYTHON_VERSION: "3.11"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          architecture: "x64"
          cache: pip

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install npm dependencies
        run: npm ci

      - name: Build and test
        run: npm test
