name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

env:
  FORCE_COLOR: 2
  NODE: 24
  PYTHON_VERSION: "3.14"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 #v7.0.0
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          architecture: "x64"
          cache: pip

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install npm dependencies
        run: npm ci

      - name: Build and test
        run: npm test
